name: Deploy to GitHub Pages

on:
  release:
    types: [published]

permissions:
  contents: write
  contents: read
  packages: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Extract tag
        id: vars
        shell: bash
        run: | 
          if [[ -n "${{ github.event.release.tag_name }}" ]]; then 
            echo "tag=${{ github.event.release.tag_name }}" >> "$GITHUB_OUTPUT"
          else 
            echo "tag=${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"
          fi

 